# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

defaults: &defaults
  working_directory: ~/tailwind-react-primitives
  docker:
    - image: circleci/node:stretch

setupGit: &setupGit
  run: |
    git config user.email "$GH_EMAIL" &&
    git config user.name "$GH_USERNAME"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint code
          command: npm run lint

      - run:
          name: Run unit tests
          command: npm test

      - run:
          name: Run build
          command: npm run build

      - run:
          name: Run styleguide generation
          command: npm run docs

      - persist_to_workspace:
          root: ./
          paths: .

  deploy-and-publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./

      - run:
          name: Deploy to GitHub
          command: npm run docs:deploy

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish package
          command: npm publish

  greenkeeperUpdateLockFile:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Update package-lock.json
          command: npm install

      - <<: *setupGit

      - run:
          name: Commit lockfile if changed
          command: |
            if ! git diff-index --quiet HEAD --; then
              git add package-lock.json &&
              git commit -m "chore(package): update lockfile [skip ci]" &&
              export URL=$(echo $CIRCLE_REPOSITORY_URL | cut -c 4- | tr : /) &&
              git push https://${GH_TOKEN}${URL} $CIRCLE_BRANCH --quiet
            fi

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - greenkeeperUpdateLockFile:
          filters:
            branches:
              only: /^greenkeeper\/.*/
      - deploy-and-publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
